Development
Macatuz/MicroversepathwrightGoogleHomepageClone pull request #2
Opened 2019-03-25 21:33 UTC by Macatuz

First code review.

2019-03-25 22:05 UTC, inhaq requested changes
Good work on your first project 🏆
Here are a few things to fix and improve:

 - Fix your errors by validating it [here](https://validator.w3.org)
 - Improve design by looking it more like YouTube. You can improve search bar, add logo, text to sidebar etc.
 - Add ReadMe file to the repository to add details about your project.

Once fixed, kindly resubmit and add me(Inzi) as project reviewer. Happy Coding 😊

2019-03-26 13:56 UTC, Ispirett commented
Thanks for your feed back will do

On Mon, Mar 25, 2019 at 6:05 PM Inzimam Ul Haq <notifications@github.com>
wrote:

> *@inhaq* requested changes on this pull request.
>
> Good work on your first project 🏆
> Here are a few things to fix and improve:
>
>    - Fix your errors by validating it here <https://validator.w3.org>
>    - Improve design by looking it more like YouTube. You can improve
>    search bar, add logo, text to sidebar etc.
>    - Add ReadMe file to the repository to add details about your project.
>
> Once fixed, kindly resubmit and add me(Inzi) as project reviewer. Happy
> Coding 😊
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Macatuz/MicroversepathwrightGoogleHomepageClone/pull/2#pullrequestreview-218609008>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AlAQD5afPALlXj6YRurcaSv7Oalondz-ks5vaUgRgaJpZM4cJcKH>
> .
>

2019-03-27 18:50 UTC, inhaq approved these changes
### Amazing work on your first project 🏆
I really liked dark-mode navbar, it's designed very clean.
Everything looks good. I would also recommend to not use `id` in your next projects.
Go ahead and submit project completion form and no need to submit for review again this project. Happy Coding 😊

2019-03-27 18:50 UTC, inhaq commented on css/main.css
> +  text-align: center;
`text-align: center;` need to be removed to make it look better

2019-03-27 20:12 UTC, merged